hw7/hasker/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
]

hw7/app/models/questions.py
from django.conf import settings
from django.db import models

from .tags import Tag


class Question(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,
                               related_name='questions')
    
    text = models.TextField()
    
    votes = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                   blank=True,
                                   related_name='questions')
    
    title = models.CharField(null=False,
                             max_length=255)
    
    tags = models.ManyToManyField(Tag,
                                  blank=True,
                                  related_name='questions',
                                  max_length=3)

    def __str__(self):
        return self.title

hw7/app/forms/question.py
from django import forms
import re

from ..models.questions import Question


def tags_validation(inp):
    if not re.match(r'^\w*[,?\s?\w+]+$', inp):
        raise forms.ValidationError("Разделите теги запятой")


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ('title', 'content', 'tags')
        widgets = {
            'title': forms.TextInput(
                attrs={'class': 'form-control-sm', 'placeholder': "Enter title"}),
            'content': forms.Textarea(attrs={
                'class': 'form-control-sm', 'placeholder': "Enter text a question"}),
            'tags': forms.TextInput(attrs={
                'class': 'form-control-sm', 'placeholder': "Enter tags with ,"})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['tags'].validators = [tags_validation]
        self.fields['tags'].help_text = "Разделите теги запятой"

hw7/app/templates/qa/ask.html
{% extends "base.html" %}

{% block extra_head %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-tagsinput/1.3.6/jquery.tagsinput.min.js"></script>
{% endblock %}

{% block content %}
<h2>Ask a question</h2>
<form class="ui form" method="post">
    {% csrf_token %}
    {% for field in form %}
    <p>
        <b>{{ field.label }}</b>
        {{ field }}
        {% if field.errors %}
        <div class="ui red message">
            {{ field.errors }}
        </div>
        {% endif %}
    </p>
    {% endfor %}
    <input class="ui primary button" type="submit" value="Ask" />
</form>
{% endblock %}

{% block javascript %}
<script>
$('#id_tags').tagsInput({
    width: 'auto',
    height:'50px',
    'onAddTag': (tag) => {
        if ($('#id_tags_tagsinput a').length > 3) {
            $('#id_tags').removeTag(tag);
        }
    },
});
</script>
{% endblock %}

hw7/app/templates/qa/index.html
{% extends "base.html" %}

{% block content %}
<div class="ui center aligned grid" style="margin-top: 0px;">
<div class="ui secondary menu">
    <a href="{% url 'qa:index' %}" class="{% if not request.GET.order %}active{% endif %} item">
        <h3>New questions</h3>
    </a>
    <a href="{% url 'qa:index' %}?order=votes" class="{% if request.GET.order %}active{% endif %} item">
        <h3>Hot questions</h3>
    </a>
</div>
</div>

<div id="questions" class="ui divided items">
{% for question in questions %}
    <div class="item">
        <div class="content">
            <a href="{{ question.get_absolute_url }}" class="header">{{ question.title }}</a>
            <div class="meta">
                asked by {{ question.author.username }} | {{ question.created_at|timesince }} ago
            </div>
            <div class="description">
                <p>{{ question.text|truncatechars:200 }}</p>
            </div>
            <div class="extra">
                <div class="ui label">Votes<div class="detail">{{ question.total_votes }}</div></div>
                {% if question.answered %}
                    <div class="ui green label">
                {% else %}
                    <div class="ui label">
                {% endif %}
                Answers<div class="detail">{{ question.answers.count }}</div></div>
                {% for tag in question.tags.all %}
                    <a href="{% url 'qa:search' %}?q=tag:{{ tag.name }}" class="ui blue label">{{ tag.name }}</a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% if is_paginated %}
<div class="ui pagination menu">
    {% if page_obj.has_previous %}
    <a class="item" href="?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.order %}&order=votes{% endif %}">&laquo;</a>
    {% endif %}

    {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
            <a class="active item">{{ i }}</a>
        {% else %}
            <a href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.order %}&order=votes{% endif %}" class="item">{{ i }}</a>
        {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
        <a class="item" href="?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}{% if request.GET.order %}&order=votes{% endif %}">&raquo;</a>
    {% endif %}
</div>
{% endif %}

{% endblock %}

hw7/app/templates/qa/question.html
{% extends "base.html" %}

{% load staticfiles %}

{% block content %}
<div class="ui black segment">
    <div class="ui items">
        <div class="item">
            <div class="ui tiny image">
                <img src="{{ question.author.profile.avatar.url }}">
            </div>
            <div class="content">
                <div class="header">
                    <h2>{{ question.title }}</h2>
                </div>
                <div class="description">
                    {{ question.text }}
                </div>
                <div class="extra">
                    <p>Asked by {{ question.author.username }} | {{ question.created_at|timesince }} ago</p>

                    <!-- Votes -->
                    {% if user.is_authenticated and user != question.author %}
                    <div id="question-vote-{{ question.id }}">
                        <a href="/question/{{ question.id }}/vote" class="vote" data-target="#question-vote-{{ question.id }}" data-value="-1"><i class="arrow red down icon"></i></a>
                        <i class="ui label"><span>{{ question.total_votes }}</span></i>
                        <a href="/question/{{ question.id }}/vote" class="vote" data-target="#question-vote-{{ question.id }}" data-value="1"><i class="arrow teal up icon"></i></a>
                    </div>
                    {% else %}
                        <i id="question_vote" class="ui label">Votes: {{ question.total_votes }}</i>
                    {% endif %}

                    <!-- Tags -->
                    {% for tag in question.tags.all %}
                        <a href="{% url 'qa:search' %}?q=tag:{{ tag.name }}" class="ui blue label">{{ tag.name }}</a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="ui divided items">
{% for answer in answers %}
    <div class="item">
        <div class="ui tiny image">
            <img src="{{ answer.author.profile.avatar.url }}">
        </div>
        <div class="content">
            <p>{{ answer.text }}</p>
            <div class="extra">
                <p>Answered by {{ answer.author.username }} | {{ answer.created_at|timesince }} ago</p>

                <!-- User can't vote for own answer -->
                {% if user.is_authenticated and user != answer.author %}
                <div id="answer-vote-{{ answer.id }}">
                    <a href="/answer/{{ answer.id }}/vote" class="vote" data-target="#answer-vote-{{ answer.id }}" data-value="-1"><i class="arrow red down icon"></i></a>
                    <i class="ui label"><span>{{ answer.total_votes }}</span></i>
                    <a href="/answer/{{ answer.id }}/vote" class="vote" data-target="#answer-vote-{{ answer.id }}" data-value="1"><i class="arrow teal up icon"></i></a>
                </div>
                {% else %}
                    <i class="ui label">Votes: {{ answer.total_votes }}</i>
                {% endif %}

                <!-- Only author of question can mark answer -->
                {% if user == question.author %}
                    {% if answer.answer %}
                        <a href="/answer/{{ answer.id }}/mark" class="mark ui right floated green label">
                    {% else %}
                        <a href="/answer/{{ answer.id }}/mark" class="mark ui right floated grey label">
                    {% endif %}
                    <i class="checkmark icon"></i>mark</a>
                {% else %}
                    {% if answer.answer %}
                        <i class="ui right floated green label"><i class="checkmark icon"></i></i>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}
</div>

{% if answers.has_other_pages %}
<div class="ui center aligned grid" style="margin-bottom: 5px;">
<div class="ui pagination menu">
    {% if answers.has_previous %}
        <a class="item" href="?page={{ answers.previous_page_number }}">&laquo;</a>
    {% endif %}

    {% for i in answers.paginator.page_range %}
        {% if answers.number == i %}
            <a class="active item">{{ i }}</a>
        {% else %}
            <a href="?page={{ i }}" class="item">{{ i }}</a>
        {% endif %}
    {% endfor %}

    {% if answers.has_next %}
        <a class="item" href="?page={{ answers.next_page_number }}">&raquo;</a>
    {% endif %}
</div>
</div>
{% endif %}

{% if user.is_authenticated %}
    <div class="ui divider"></div>
    <h3>Your answer:</h3>
    <form class="ui form" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="ui primary button" type="submit" value="Answer" />
    </form>
{% endif %}
{% endblock %}

{% block javascript %}
<script src="{% static 'js/main.js' %}"></script>
<script src="{% static 'js/qa.js' %}"></script>
{% endblock %}